### ISSUE TITLE
IOException in HFST-Wrapper 

### ISSUE THREAD

**Issue by DavidNemeskey** [dlt-rilmta/hunlp-GATE#20]
I get `IOException`s (more often `IO Exception` -- I guess it depends on where the error occurs, i.e. enough words are written to the `stdin` of the dead process) for some input to the HFST `Analyzer` module.

Example output:
```
IO Exception: null
IO Exception: null
IO Exception: null
IO Exception: null
IO Exception: null
IO Exception: null
IO Exception: null
java.io.IOException: Broken pipe
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at hu.nytud.hfst.Analyzer$WorkerProcess.write(Analyzer.java:218)
	at hu.nytud.hfst.Analyzer$WorkerProcess.run(Analyzer.java:206)
	at java.lang.Thread.run(Thread.java:745)
```

Example input from the Hungarian Webcorpus: 
[ioexception.input.txt](https://github.com/dlt-rilmta/hunlp-GATE/files/674147/ioexception.input.txt)

The culprit is the very long token _Pécs-Nagykanizsa-Graz-Aussee-Ischl-Salzburg-Zürich-Luzern-Rigire-Zürich-München-Linz-Bécs-Győr-Mohács-Pécs_, but presumable other inputs could induce the error as well. What is strange is that if I run `hfst-lookup` with the same parameters it is run by GATE:
```
cat ioexception.input.txt | ../linux/hfst-lookup.sh --cascade=composition --xfst=print-pairs --xfst=print-space --pipe-mode -t 2 ../hu.hfstol
```
, it is processed without a hitch.

**Comment by DavidNemeskey** [comment]
The full example. I first ran it through quntoken (`quntoken qterror.txt`), and parsed the non-ws tokens from it. The resulting file is _qterror.tokens.txt_. Then I ran _hfst-lookup_ on it, as described above, and no errors. I then tried it with GATE, and got the aforementioned problems. I also printed all tokens sent to HFST-Wrapper, and it is exactly the same as _qterror.tokens.txt_. So the error must be in the wrapper somewhere.

[qterror.txt](https://github.com/dlt-rilmta/hunlp-GATE/files/726312/qterror.txt)

[qterror.tokens.txt](https://github.com/dlt-rilmta/hunlp-GATE/files/726315/qterror.tokens.txt)
