### ISSUE TITLE
Magyarlánc Depparse crashes with long/special input

### ISSUE THREAD

**Issue by mmihaltz** [dlt-rilmta/hunlp-GATE#4]
GATE 8.1 on Linux
source text URL: http://index.hu/tudomany/2016/01/12/zavar_van_a_gravitacios_hullamok_korul/

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 2
    at java.lang.String.charAt(String.java:658)
    at hu.u_szeged.pos.converter.MSDToCoNLLFeatures.parseA(MSDToCoNLLFeatures.java:228)
    at hu.u_szeged.pos.converter.MSDToCoNLLFeatures.convert(MSDToCoNLLFeatures.java:731)
    at hu.u_szeged.dep.parser.MateParserWrapper.parseSentence(MateParserWrapper.java:44)
    at hu.nytud.gate.parsers.MagyarlancDependencyParser.parseSentence(MagyarlancDependencyParser.java:143)
    at hu.nytud.gate.parsers.MagyarlancDependencyParser.execute(MagyarlancDependencyParser.java:93)
    at gate.util.Benchmark.executeWithBenchmarking(Benchmark.java:291)
    at gate.creole.ConditionalSerialController.runComponent(ConditionalSerialController.java:163)
    at gate.creole.SerialController.executeImpl(SerialController.java:157)
    at gate.creole.ConditionalSerialAnalyserController.executeImpl(ConditionalSerialAnalyserController.java:225)
    at gate.creole.ConditionalSerialAnalyserController.execute(ConditionalSerialAnalyserController.java:132)
    at gate.util.Benchmark.executeWithBenchmarking(Benchmark.java:291)
    at gate.gui.SerialControllerEditor$RunAction$1.run(SerialControllerEditor.java:1728)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by sassbalint** [comment]
Obsolete, affects just Magyarlánc 2.0 but Magyarlánc 3.0 is used currently.
